const std = @import("std");
const M31 = @import("../field/m31.zig").M31;
const CirclePoint = @import("point.zig").CirclePoint;
const CircleDomain = @import("domain.zig").CircleDomain;

/// A coset of a circle subgroup: { offset ⊕ h : h ∈ H } where H is the
/// subgroup generated by `step` (order 2^log_size). Used to evaluate on
/// points strictly outside the polynomial's original subgroup, so that
/// low-degree tests (FRI) are meaningful.
pub const CircleCoset = struct {
    offset: CirclePoint,
    step: CirclePoint,
    log_size: u32,

    pub fn new(offset: CirclePoint, step: CirclePoint, log_size: u32) CircleCoset {
        return .{ .offset = offset, .step = step, .log_size = log_size };
    }

    pub fn size(self: CircleCoset) usize {
        return @as(usize, 1) << @intCast(self.log_size);
    }

    pub fn at(self: CircleCoset, index: usize) CirclePoint {
        std.debug.assert(index < self.size());
        return self.offset.add(self.step.mulScalar(@as(u64, @intCast(index))));
    }

    /// A coset of the canonical subgroup of order 2^log_size, offset by the
    /// full-circle generator so that none of its points lie in the subgroup.
    pub fn standard(log_size: u32) CircleCoset {
        const offset = CirclePoint.generator();
        const step = CirclePoint.generatorWithOrder(log_size);
        return CircleCoset.new(offset, step, log_size);
    }

    /// Halves the coset under doubling: doubles offset and step, so
    /// `at(i).double()` lands in the halved coset.
    pub fn half(self: CircleCoset) CircleCoset {
        std.debug.assert(self.log_size > 0);
        return CircleCoset.new(self.offset.double(), self.step.double(), self.log_size - 1);
    }
};

test "circle coset properties" {
    const coset = CircleCoset.standard(4);
    try std.testing.expectEqual(@as(usize, 16), coset.size());
    // all points on the circle
    for (0..coset.size()) |i| {
        try std.testing.expect(coset.at(i).onCircle());
    }
    // points are distinct
    for (0..16) |i| {
        const p = coset.at(i);
        for (0..i) |j| {
            const q = coset.at(j);
            try std.testing.expect(!(p.x.eq(q.x) and p.y.eq(q.y)));
        }
    }
    // half(): double of coset points lands in the halved coset
    const h = coset.half();
    try std.testing.expectEqual(@as(usize, 8), h.size());
    for (0..8) |i| {
        const doubled = coset.at(i).double();
        try std.testing.expect(doubled.x.eq(h.at(i).x));
        try std.testing.expect(doubled.y.eq(h.at(i).y));
    }
}

test "circle coset avoids canonical subgroup" {
    const dom = CircleDomain.standard(3);
    const coset = CircleCoset.standard(3);
    for (0..8) |i| {
        const p = coset.at(i);
        var in_domain = false;
        for (0..8) |j| {
            const q = dom.get(j);
            if (p.x.eq(q.x) and p.y.eq(q.y)) in_domain = true;
        }
        try std.testing.expect(!in_domain);
    }
}
